events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        add_header X-Env green always;
        add_header X-Release "v2" always;

        root /usr/share/nginx/html;
        index home/index.html;

        location / {
            try_files $uri $uri/ /home/index.html;
        }
    }
}